[package]
name = "emtk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[target."cfg(windows)".dependencies]
detours-sys = { workspace = true }
emf = { path = "../emf" }

[dependencies]
anyhow = "1.0.86"
# EMF is needed as a dependency so that emf.dll gets compiled before running EMTK.
chrono = { version = "0.4.38", features = ["serde"] }
dirs = "5.0.1"
emf-types = { workspace = true }
exparser = { path = "../exparser" }
human_bytes = "0.4.3"
iced = { version = "0.13.1", features = [
	"advanced",
	"markdown",
	"svg",
	"tokio",
] }
iced_aw = { version = "0.11.0", features = ["context_menu"] }
iced_core = "0.13.1"
iced_drop = { git = "https://github.com/jhannyj/iced_drop", rev = "d259ec4dff098852d995d3bcaa5551a88330636f" }
image = { version = "0.25.2", features = ["ico"] }
lilt = "0.7.0"
log.workspace = true
nucleo = "0.5.0"
open = "5.3.0"
rfd = "0.14.1"
ron = "0.8.1"
semver = "1.0.23"
serde = { workspace = true }
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.39.2", features = [
	"macros",
	"rt",
	"rt-multi-thread",
	"sync",
	"time",
] }
toml.workspace = true
ureq = { version = "2.10.0", features = ["json"] }
winapi = { workspace = true }

[build-dependencies]
# See: https://github.com/BenjaminRi/winresource/pull/22
winresource = { git = "https://github.com/BenjaminRi/winresource", rev = "3ebdb3289a8731d50e9728b2e7ee30997f537d4a" }

# emf.dll is required for emtk to inject into the game.
[package.metadata.cargo-machete]
ignored = ["emf"]
