[package]
name = "emtk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = "1.0.86"
detours-sys = { workspace = true }
# EMF is needed as a dependency so that emf.dll gets compiled before running EMTK.
emf = { path = "../emf" }
iced = { git = "https://github.com/iced-rs/iced", version = "0.13.0-dev", features = [
	"markdown",
	"tokio",
] }
iced_aw = { git = "https://github.com/iced-rs/iced_aw", rev = "0f616fe3a74b1587b94e9fb49a29c52bb93ef01c", features = [
	"drop_down",
] }
tokio = { version = "1.39.2", features = [
	"macros",
	"rt",
	"rt-multi-thread",
	"sync",
] }
serde = { workspace = true }
winapi = { workspace = true }
ureq = { version = "2.10.0", features = ["json"] }
chrono = { version = "0.4.38", features = ["serde"] }
log.workspace = true
image = { version = "0.25.2", features = ["ico"] }
semver = "1.0.23"
open = "5.3.0"
toml.workspace = true
dirs = "5.0.1"
emf-types = { workspace = true }
exparser = { path = "../exparser" }
async-stream = "0.3.5"
strum = { version = "0.26.3", features = ["derive"] }

[build-dependencies]
cbindgen = "0.26.0"
winresource = "0.1.17"

# emf.dll is required for emtk to inject into the game.
[package.metadata.cargo-machete]
ignored = ["emf"]
