[package]
name = "emtk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = "1.0.86"
detours-sys = { workspace = true }
# EMF is needed as a dependency so that emf.dll gets compiled before running EMTK.
chrono = { version = "0.4.38", features = ["serde"] }
dirs = "5.0.1"
emf = { path = "../emf" }
emf-types = { workspace = true }
exparser = { path = "../exparser" }
human_bytes = "0.4.3"
iced = { git = "https://github.com/iced-rs/iced", version = "0.13.0-dev", features = [
	"markdown",
	"svg",
	"tokio",
] }
iced_aw = { git = "https://github.com/iced-rs/iced_aw", rev = "0f616fe3a74b1587b94e9fb49a29c52bb93ef01c", features = [
	"drop_down",
] }
iced_core = { git = "https://github.com/iced-rs/iced", version = "0.13.0-dev" }
image = { version = "0.25.2", features = ["ico"] }
lilt = "0.7.0"
log.workspace = true
nucleo = "0.5.0"
open = "5.3.0"
rfd = "0.14.1"
semver = "1.0.23"
serde = { workspace = true }
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.39.2", features = [
	"macros",
	"rt",
	"rt-multi-thread",
	"sync",
	"time",
] }
toml.workspace = true
ureq = { version = "2.10.0", features = ["json"] }
winapi = { workspace = true }

[build-dependencies]
cbindgen = "0.26.0"
winresource = "0.1.17"

# emf.dll is required for emtk to inject into the game.
[package.metadata.cargo-machete]
ignored = ["emf"]
