excludes:
  - \.gitignore
  - .*lock
  - \.git/.*
  - \.licensure\.yml
  - README.*
  - LICENSE.*
  - .*\.(md|rst|txt)
  - .cargo
  - deps
  - target
  - *.toml
  - .gitmodules

licenses:
  - files: any
    ident: GPL-3.0
    authors:
      - name: ProffDea
        email: deatea@riseup.net
      - name: Megumin
        email: megumin@megu.dev
    unwrap_text: false
    template: |
      Exanima Modding Toolkit
      Copyright (C) [year] [name of author]
      SPDX-License-Identifier: GPL-3.0-only

comments:
  - extensions:
      - rs
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
