[formatting]
indent_string = "\t"
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies", "build-dependencies"]

[rule.formatting]
reorder_keys = true
