[package]
edition = "2021"
name = "emtk"
version = "0.1.0"

[workspace]
members = ["emf", "repacker", "detours"]

[workspace.dependencies]
bitstream-io = "1.7.0"
detours-sys = { path = "./detours" }
libmem = "4.2.1"
serde = { version = "1.0.190", features = ["derive"] }
toml = "0.8.6"
winapi = { version = "0.3.9", features = [
	"minwindef",
	"windef",
	"winnt",
	"processenv",
	"minwinbase",
	"winbase",
	"handleapi",
	"libloaderapi",
	"psapi",
	"winuser",
	"errhandlingapi",
	"consoleapi",
	"memoryapi",
	"processthreadsapi",
] }

[dependencies]
bitstream-io = { workspace = true }
detours-sys = { workspace = true }
libmem = { workspace = true }
repacker = { path = "./repacker" }
serde = { workspace = true }
toml = { workspace = true }
widestring = "1.0.2"
winapi = { workspace = true }
