[workspace]
resolver = "2"
members = ["crates/*", "bindings/python/*", "bindings/rust/*", "examples/*"]
default-members = ["crates/emtk"]

[workspace.package]
version = "0.0.1-beta.1"
authors = ["Megumin <megumin@megu.dev>", "ProffDea <deatea@riseup.net>"]
edition = "2021"
documentation = "https://exanimamodding.codeberg.page/Book"
homepage = "https://exanimamodding.codeberg.page/Book"
repository = "https://codeberg.org/ExanimaModding/Toolkit"
license = "GPL-3.0-only"

[workspace.dependencies]
detours-sys = { path = "./crates/detours" }
emf-types = { path = "./crates/emf-types" }
log = "0.4.21"
pretty_env_logger = "0.5.0"
safer-ffi = { version = "0.1.8", default-features = false, features = [
	"alloc",
	"log",
] }
serde = { version = "1.0.190", features = ["derive"] }
toml = "0.8.6"
winapi = { version = "0.3.9", features = [
	"minwindef",
	"winnt",
	"winbase",
	"errhandlingapi",
	"psapi",
	"consoleapi",
] }
