[workspace]
resolver = "2"
members = ["crates/*", "bindings/rust/*", "examples/*"]
default-members = ["crates/emtk"]

[workspace.package]
# Update the version in the following files when changing the version number:
# - ./bindings/python/emtk-py/emtk/blender/blender_manifest.toml
# - ./crates/xtask/src/main.rs
version = "0.1.0-beta.1"
authors = ["Megumin <megumin@megu.dev>", "ProffDea <deatea@riseup.net>"]
edition = "2021"
documentation = "https://exanimamodding.codeberg.page/Book"
homepage = "https://exanimamodding.codeberg.page/Book"
repository = "https://codeberg.org/ExanimaModding/Toolkit"
license = "LGPL-3.0-or-later"

[workspace.dependencies]
detours-sys = { path = "./crates/detours" }
emf-types = { path = "./crates/emf-types" }
log = "0.4"
pretty_env_logger = "0.5"
safer-ffi = { version = "0.1", default-features = false, features = [
	"alloc",
	"log",
] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
tracing = "0.1"
toml = "0.8"
winapi = { version = "0.3", features = [
	"minwindef",
	"winnt",
	"winbase",
	"errhandlingapi",
	"psapi",
	"consoleapi",
	"ntdef",
] }
