[package]
edition = "2021"
name = "emtk"
version = "0.1.0"

[workspace]
members = [
  "emf",
  "repacker",
  "detours",
]

[dependencies]
bitstream-io = "1.7.0"
detours-sys = {path = "./detours"}
libmem = "4.2.1"
repacker = {path = "./repacker"}
serde = {version = "1.0.190", features = ["derive"]}
toml = "0.8.6"
widestring = "1.0.2"
winapi = {version = "0.3.9", features = ["minwindef", "windef", "winnt", "minwinbase", "processthreadsapi", "handleapi"]}

[build-dependencies]
cmake = "0.1.50"
winreg = "0.52.0"
