[package]
edition = "2021"
name = "emtk"
version = "0.1.0"

[workspace]
members = ["emf", "repacker", "detours"]

[workspace.dependencies]
bitstream-io = "1.7.0"
detours-sys = { path = "./detours" }
serde = { version = "1.0.190", features = ["derive"] }
toml = "0.8.6"
winapi = { version = "0.3.9", features = [
	"minwindef",
	"winnt",
	"winbase",
	"handleapi",
	"libloaderapi",
	"psapi",
	"errhandlingapi",
	"consoleapi",
	"memoryapi",
	"processthreadsapi",
	"processenv",
] }

[dependencies]
detours-sys = { workspace = true }
winapi = { workspace = true }
# EMF is needed as a dependency so that emf.dll gets compiled before running EMTK.
emf = { path = "./emf" }

[build-dependencies]
cbindgen = "0.26.0"


[package.metadata.cargo-machete]
ignored = ["emf"]
