[workspace]
resolver = "2"
members = ["crates/*", "examples/*"]

[workspace.dependencies]
bitstream-io = "2.5.0"
detours-sys = { path = "./crates/detours" }
dynasmrt = "2.0.0"
log = "0.4.21"
pretty_env_logger = "0.5.0"
safer-ffi = { version = "0.1.8", default-features = false, features = [
	"alloc",
	"log",
] }
serde = { version = "1.0.190", features = ["derive"] }
toml = "0.8.6"
winapi = { version = "0.3.9", features = [
	"minwindef",
	"winnt",
	"winbase",
	"errhandlingapi",
	"psapi",
	"consoleapi",
] }
