# Why Cargo Make?
# Cargo has a LOT of annoying limitations, such as compiling different targets in a workspace.
# Cargo Make is a build system that allows us to do that.
# Instead of running `cargo build --target <target> -p <project>` you can just run `cargo make <project>`.

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.clean]
args = ["clean"]
command = "cargo"

[tasks.emf]
args = ["build", "-p", "emf", "--target", "i686-pc-windows-msvc", "--out-dir", "target/dist", "-Z", "unstable-options"]
command = "cargo"

[tasks.repacker]
args = ["build", "-p", "repacker", "--target", "x86_64-pc-windows-msvc", "--out-dir", "target/dist", "-Z", "unstable-options"]
command = "cargo"

[tasks.emtk]
args = ["build", "-p", "emtk", "--target", "x86_64-pc-windows-msvc", "--out-dir", "target/dist", "-Z", "unstable-options"]
command = "cargo"

[tasks.build]
clear = true
dependencies = [
  "emf",
  "repacker",
  "emtk",
]
