[plugin]
id = "dev.megu.demo-plugin"
name = "Demo Plugin"
description = """
A demo plugin showcasing the rust bindings.

It includes:
- Partial God Hand.
- A very flawed God Mode that makes you (and everyone else) invincible.
"""
version = "1.0.0"
supported_versions = ["1.0.0"]
url = "https://codeberg.org/ExanimaModding/Toolkit/src/branch/main/examples/demo-plugin"
executable = "demo-plugin.dll"
enabled = true

[plugin.author]
name = "Megumin"
contact = "https://codeberg.org/ExanimaModding/Toolkit/issues"
url = "https://github.com/MeguminSama"

[[setting]]
name = "Enable Godode"
id = "godmode_enabled"
description = "Enable god mode (wip)."
default = true

[[setting]]
name = "Enable GodHand"
id = "godhand_enabled"
description = "Enable god hand (wip)."
default = true
