[package]
edition = "2021"
name = "emf"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]
required-features = []

# To generate headers:
# cargo run -p emf --features headers --bin generate-headers

[[bin]]
name = "generate-headers"
required-features = ["headers"]

[dependencies]
libmem = { git = "https://github.com/rdbo/libmem.git", rev = "bd2aaf2d99eafd7c7cb87bfcb925ec94c593062f" }
libmem-sys = { git = "https://github.com/rdbo/libmem.git", rev = "bd2aaf2d99eafd7c7cb87bfcb925ec94c593062f" }
log = { workspace = true }
detours-sys = { workspace = true }
dynasmrt = { workspace = true }
pelite = "0.10.0"
serde = { workspace = true }
winapi = { workspace = true }
libloading = "0.8.3"
anyhow = "1.0.86"
once_cell = "1.19.0"
pretty_env_logger = { workspace = true }
safer-ffi = { workspace = true }
toml.workspace = true
path-clean = "1.0.1"

[features]
headers = ["safer-ffi/headers"]
