[package]
name = "godhand"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dynasmrt = { workspace = true }
log = { workspace = true }
once_cell = "1.19.0"
pretty_env_logger = { workspace = true }
safer-ffi = { workspace = true }
