[plugin]
id = "dev.megu.godhand"
name = "GodHand"
description = "A plugin that allows you to move any item, from any distance."
version = "1.0.0"
supported_versions = ["1.0.0"]
url = "https://codeberg.org/ExanimaModding/Mods/src/branch/main/GodHand"
executable = "dev.megu.godhand.dll"

[plugin.author]
name = "Megu"
contact = "megumin@megu.dev"
url = "https://github.com/MeguminSama"

[[setting]]
name = "Enable GodHand"
description = "Enable or disable God Hand."
default = true

[[setting]]
name = "Example Setting 1"
description = "This is an example setting."
default = "Hello, World!"

[[setting]]
name = "Example Setting 2"
description = "Set the answer to life, the universe, and everything."
default = 42
