[plugin]
id = "dev.megu.godhand"
name = "GodHand"
description = "A plugin that allows you to move any item, from any distance."
version = "1.0.0"
supported_versions = ["1.0.0"]
url = "https://codeberg.org/ExanimaModding/Toolkit/src/branch/main/examples/godhand"
executable = "godhand.dll"
enabled = false

[plugin.author]
name = "Megu"
contact = "https://codeberg.org/ExanimaModding/Toolkit/issues"
url = "https://github.com/MeguminSama"

[[setting]]
name = "Range Limit for Placement"
id = "range_limit_for_placement"
description = "Patch the range limit for object placement."
default = true

[[setting]]
name = "Range Limit for Reach"
id = "range_limit_for_reach"
description = "Patch the range limit for hand reach."
default = true

[[setting]]
name = "Disable Range Limit for Door and Lever Reach"
id = "range_limit_for_door_and_lever_reach"
description = "Patch the range limit for door and lever reach."
default = true

[[setting]]
name = "Disable Weight Limit"
id = "weight"
description = "Patch the weight limit."
default = true

[[setting]]
name = "Interact while fallen"
id = "interact_while_fallen"
description = "Patch the ability to interact while fallen."
default = true

[[setting]]
name = "Don't Interrupt if fallen"
id = "dont_interrupt_if_fallen"
description = "Patch the ability to interrupt if fallen."
default = true
