[alias]
xtask = "run -p xtask --"
xr = "xwin run --target x86_64-pc-windows-msvc"
xb = "xwin build --target x86_64-pc-windows-msvc"
release = "build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --release --"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = ["-Zshare-generics=y", "-Zthreads=0"]
