[plugin]
id = "dev.megu.godmode"
name = "GodMode"
description = "A very flawed plugin that makes you invincible! Kinda?"
version = "1.0.0"
supported_versions = ["1.0.0"]
url = "https://codeberg.org/ExanimaModding/Toolkit/src/branch/main/examples/godmode"
executable = "godmode.dll"
enabled = false

[plugin.author]
name = "Megu"
contact = "https://codeberg.org/ExanimaModding/Toolkit/issues"
url = "https://github.com/MeguminSama"

[[setting]]
name = "Example Setting 1"
id = "example_setting_1"
description = "This is an example setting."
default = "Hello, World!"

[[setting]]
name = "Example Setting 2"
id = "example_setting_2"
description = "Set the answer to life, the universe, and everything."
default = 42
