[package]
name = "emf-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
emf-types = { workspace = true }
safer-ffi = "0.1.9"

[build-dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
ureq = { version = "2.10.0", features = ["json"] }
zip = "2.1.5"
