[package]
name = "detours-sys"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true
repository.workspace = true
license = "MIT"

[build-dependencies]
bindgen = "0.71"
cc = "1.2"
cmake = "0.1"
