[package]
name = "detours-sys"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = "MIT"

[build-dependencies]
bindgen = "0.69.1"
cc = "1.0.83"
cmake = "0.1.50"
