[package]
edition = "2021"
name = "emf"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
required-features = []

[dependencies]
detours-sys = {workspace = true}
dynasmrt = "2.0.0"
emf-ui = {path = "../emf-ui"}
env_logger = {workspace = true}
exe = "0.5.6"
lazy_static = "1.4.0"
libmem = {workspace = true}
mlua = {version = "0.9.2", features = ["luajit", "vendored", "macros"]}
pelite = "0.10.0"
serde = {workspace = true}
winapi = {workspace = true}
